# Generated by Django 5.0.3 on 2024-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tekno', '0002_producto_descripcion_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default='0'),
        ),
    ]
