# Generated by Django 5.0.3 on 2024-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tekno', '0006_producto_tipo_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
