# Generated by Django 5.0.3 on 2024-10-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tekno', '0007_remove_cliente_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
